spring:
    application:
        name: spring-starter
    datasource:
        url: jdbc:postgresql://localhost:5432/ecommerce
        username: admin
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true